### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by guigzzz** [KillingSpark/sparkzstd#2]
I've done a simple `git clone` of this project outside of GOPATH (i.e. to use go modules), and when I execute `go build`, I get:

```
can't load package: package github.com/killingspark/sparkzsdt: unknown import path 
"github.com/killingspark/sparkzsdt": cannot find module providing package github.com/killingspark/sparkzsdt
``` 

I'm guessing you need to make that repo public.

**Comment by guigzzz** [comment]
Just noticed it's a typo in the package name.

**Comment by guigzzz** [comment]
ok turns out I needed to `cd cmd/sparkzstd` for it to build. Not sure if this still counts as an issue.

**Comment by KillingSpark** [comment]
The text in the Readme is somewhat unclear thats right, I will update it with build instructions. 

Note that the cmd/sparkzstd/main.go currently is not a decompressor like you would have when using `zstd -d`. I use this for testing the decompression against original files. I will add a cmd/zstd/main.go which will act like `zstd -d` in the future.

**Comment by KillingSpark** [comment]
Updated the readme.
